# Generated by Django 5.1.3 on 2025-07-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_todo', '0002_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority_score',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3),
        ),
        migrations.AlterField(
            model_name='contextentry',
            name='source_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_score',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1),
        ),
    ]
